### ISSUE TITLE
Run both the admission controller and the secrets injector as non-root

### ISSUE THREAD

**Issue by dinukadev** [ecrousseau/aws-secret-injector#2]
Please find the attached patch file that makes it possible to run both the admission controller and the secrets injector pod as non-root. This also mounts the file group as nogroup to further lockdown the permissions of the secrets injected.

Would be great if any review comments are provided on the same.

[run_as_non_root.patch.txt](https://github.com/ecrousseau/aws-secret-injector/files/5897425/run_as_non_root.patch.txt)

**Comment by ecrousseau** [comment]
Thanks @dinukadev. I've reviewed your patch and also looked closely at how Kubernetes manages security contexts and filesystem permissions, and have come to the following conclusions:

1. The user the admission controller runs as is completely separate from the user the init container runs as; we can change them individually
2. Focusing on the init container for now: I think the correct place to set the user and group for the init container is at the pod level, for two reasons:
    a. The PodSecurityContext object sets the fsGroup and I don't see any way to do this at the container level, and the init container needs to match that group so it can write files to the volume
    b. To ensure that the application container(s) can read the files created by the init container, they should run as the same user/group, and we can ensure this is the case by *not* setting a user for the init container, so it will follow the PodSecurityContext
3. We *should* set ReadOnlyRootFilesystem, AllowPrivilegeEscalation, and Privileged in the init container's security context
4. We *should* set the admission controller itself to run as non-root etc.

I'll push a change to cover point 3 and I'll make a future change for point 4.

To cover your "run as non-root user" requirement please set a [pod-level security context](https://v1-16.docs.kubernetes.io/docs/reference/generated/kubernetes-api/v1.16/#podsecuritycontext-v1-core). Make sure you set the fsGroup to the same group that the pod will run as.

**Comment by dinukadev** [comment]
@ecrousseau thank you for the review.

On point. 

> To ensure that the application container(s) can read the files created by the init container, they should run as the same user/group, and we can ensure this is the case by not setting a user for the init container, so it will follow the PodSecurityContext

As you set the file permission to 755 when writing the secrets exploded as a JSON, wouldnt the permissions issue be covered from that?

To add on, im not sure if there was a particular reason, but cant we run the admission controller as a. DaemonSet rather than a Deployment?

Do you need me to send an update patch or would you be doing the changes?

Also, are you happy with me adding the security context when the init container is initialised from the admission controller?

Thanks again for taking the time to review.

**Comment by dinukadev** [comment]
> `I think the correct place to set the user and group for the init container is at the pod level,`

Agreed on this point.

**Comment by ecrousseau** [comment]
@dinukadev  I've pushed through changes already, and will create a release as soon as I'm done testing 👍 

You are right that the created files have "everyone can read" permissions, so I guess the exact owner of the file is not really a big deal, but the PodSecurityContext will keep it all the same for us anyway.

I don't see any reason to run the admission controller as a DaemonSet - it doesn't interact with the node in any way, so there's no need to have a replica on every node. There just needs to be at least one replica available to handle requests coming from the cluster API via the MutatingWebhookConfiguration.

**Comment by ecrousseau** [comment]
https://github.com/ecrousseau/aws-secret-injector/releases/tag/v1.5
